name: Main pipeline

on: push

jobs:
  call-deploy:
    uses: negiabhay/github-actions-intermediate/.github/workflows/reusable-deploy.yml@main
    with:
      environment: Production
      app_name: quickbite-api
