name: Smart pipeline V2

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Download the code
        uses: actions/checkout@v4

      - name: Step 2 - Run test
        run: |
          echo "Running test"
          echo "All test passed"

      - name: Notify if test failed
        if: failure()
        run: echo "Alert test failed! -- Notifying team"

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Step 1 - Bundle the App
        run: echo "Building app only on main branach"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.actor == 'negiabhay'
    steps:
      - name: Step 1 - Deploy on server
        run: echo "Deploying on server"
